### ISSUE TITLE
[stylelint] rule swissquote/no-type-outside-scope

### ISSUE THREAD

**Issue by alexandratodiruta** [swissquote/crafty#11]
Stylelint reports the rule `swissquote/no-type-outside-scope` four times instead of one for the following: 

```scss
.Section--news a:focus {
    .MediaObject, .MediaObject__content {
        overflow: visible;
    }

    .MediaObject__content__first {
        box-shadow: 0 0 2px 2px var(--color-focus);
    }

    .MediaObject__content__secondary {
        margin-left: 1rem;
    }
}
```

```
 134:5   ✖  Types are allowed only inside a scope                                   swissquote/no-type-outside-scope  
 134:5   ✖  Types are allowed only inside a scope                                   swissquote/no-type-outside-scope  
 138:5   ✖  Types are allowed only inside a scope                                   swissquote/no-type-outside-scope  
 142:5   ✖  Types are allowed only inside a scope                                   swissquote/no-type-outside-scope
