### ISSUE TITLE
Custom properties don't work properly with color()

### ISSUE THREAD

**Issue by onigoetz** [swissquote/crafty#1270]
```css
:root { --color-light: #d1d1d1; }

.Button { color: color(var(--color-light) tint(90%)); }
```

Will not work as expected when custom properties are supported by all target browsers 
- since the browsers are supported, custom properties aren't resolved
- since custom properties aren't resolved, the color function doesn't know the color it has to transform.

Described here : https://github.com/postcss/postcss-color-function/issues/49

apparently postcss-color-mod-function solves this issue, we should provide a backwards compatibility to the `color()` function though
